### ISSUE TITLE
Custom header for generated requests

### ISSUE THREAD

**Issue by Caychu** [christianhelle/httpgenerator#148]
**Is your feature request related to a problem? Please describe.**
I want to create Requests with a special header that is not described inside of the openapi.yml. This is needed for some services that require this header

**Describe the solution you'd like**
I want to create Requests with a special header that is not described inside of the openapi.yml

**Describe alternatives you've considered**
Solution would be an option like where I can add a list of custom headers

**Comment by Caychu** [comment]
@christianhelle yes exactly. Maybe there is a way to provide more then one header. I only need one custom header for my use case

**Comment by christianhelle** [comment]
@Caychu We could allow multiple instances of the argument, like this

```
--custom-header "X-Custom-Header-1: Some Value" --custom-header "X-Custom-Header-2: Some Value"
```

**Comment by Caychu** [comment]
Sounds perfect
