### ISSUE TITLE
Reference Token from environment file

### ISSUE THREAD

**Issue by CTBT** [christianhelle/httpgenerator#51]
**Is your feature request related to a problem? Please describe.**
The cli option "authorization-header" creates a variable "@authorization" inside each of the generated .http files and sets the given token as value. This is fine as long the token is valid. After invalidation currently you have to update the token in each .http file. This is not practical for al lot of files and can´t be set in a manually generated .env.json file because it is overriden by the invalid token value.

**Describe the solution you'd like**
My solution would be to remove the statement for setting of the "@authorization" variable and instead create a .env.json file that contains the token value which is then referenced in all the .http files. 

**Describe alternatives you've considered**
Even just not generating the set statement would be helpful because then the variable can be set in a manually generated .env.json file.

**Comment by christianhelle** [comment]
@CTBT thanks for taking the time to report this.

I'm fairly new to .http files and I use it as a replacement for Swagger UI. So when I built the tool my workflow was still very similar to how I would use Swagger UI to debug/test my HTTP API's, which would be to have a fresh set of .http files every time I launch the debugger

I haven't tried working with `.env.json` files yet but I'll look into this. Someone else has mentioned this to me recently as well. My current approach to generating .http files would always be through a script that I would create for each system I use. I eventually  ended up with scripts that update the `@authorization` variable

Do you know if you can have multiple `.env.json` files and how to specify which environment to use? Any non-trivial help and clues would be greatly appreciated. I will of course try and see what I can figure out myself by reading the docs, but any help would be awesome

Thanks
