### ISSUE TITLE
Multiple variable definition 

### ISSUE THREAD

**Issue by CTBT** [christianhelle/httpgenerator#52]
**Describe the bug**
When i generate the .http file with the output-type set to "OneFile" the generated file contains several requests that define a variable with the same name. This leads to multiple variable definition statements of the same variable which leads to an error. 

`
### foo
@id = 0

GET http://test.com/foo{{id}}

### bar
@id = 0

GET http://test.com/bar{{id}}
`

`Cannot execute request, because it references ambiguous variable 'id'`

<img width="465" alt="grafik" src="https://github.com/christianhelle/httpgenerator/assets/22419230/11f8922b-8b4e-4b34-a33f-811605148b61">

**Support Key**: `[my-support-key]`

**Comment by christianhelle** [comment]
@CTBT Sorry for the delay, it took some effort but I finally found time to work on this...

I have a solution that will prefix the route variables with the a unique operation name so generating a single file output will can look something like this:

```
@contentType = application/json


################################################################################################################
### Request: GET /pet/findByTags
### Summary: Finds Pets by tags
### Description: Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
################################################################################################################

### Query Parameter: Tags to filter by
@GetFindPetsByTags_tags = str


GET https://petstore3.swagger.io//api/v3/pet/findByTags
Content-Type: {{contentType}}


#######################################
### Request: GET /pet/{petId}
### Summary: Find pet by ID
### Description: Returns a single pet
#######################################

### Path Parameter: ID of pet to return
@GetPetById_petId = 0


GET https://petstore3.swagger.io//api/v3/pet/{{GetPetById_petId}}
Content-Type: {{contentType}}


##################################
### Request: DELETE /pet/{petId}
### Summary: Deletes a pet
##################################

### Path Parameter: Pet id to delete
@DeletePet_petId = 0


DELETE https://petstore3.swagger.io//api/v3/pet/{{DeletePet_petId}}
Content-Type: {{contentType}}
```

Will this work for you?

**Comment by rmunk** [comment]
@christianhelle I have found an issue with this approach. When you have endpoints with multiple route parameters the generated variable names contain curly braces which breaks the generated code. Quick solution that comes to mind would be to replace the curly braces with underscore when generating variable names.

<img width="1207" height="381" alt="Image" src="https://github.com/user-attachments/assets/d3434f22-b9d4-49f0-9ce8-becdd4a423f5" />
