### ISSUE TITLE
Multiline XML Comments are not represented ok

### ISSUE THREAD

**Issue by blogcraft** [christianhelle/httpgenerator#94]
**Describe the bug**
I Have my API with some xml documentation:
![image](https://github.com/christianhelle/httpgenerator/assets/5615323/b7035652-4505-4a32-8e9b-25afaaaff64c)

But while generating the .html file, some comments are not commented:
<img width="500" alt="image" src="https://github.com/christianhelle/httpgenerator/assets/5615323/12d63be2-562b-440d-90fb-fa3882c1e4cc">

Generating a send request where it should not be any.

These XML documentation is a must have because it explains the endpoint in the docs.
![image](https://github.com/christianhelle/httpgenerator/assets/5615323/84137c17-d2af-4df2-849c-65c2964d1900)

**Comment by christianhelle** [comment]
@blogcraft This should be trivial to fix. Thanks for reporting this. I haven't gotten around to hunting for edge cases as I mostly focused on my own needs for the tool
